worker_processes  1;

events {
  worker_connections  1024;
}

http {
  include /etc/nginx/mime.types;

  # 1. Bloque HTTP Plano (Solo para Certbot y redirección segura)
  server {
    listen 8080;
    server_name smol-ivan.xyz www.smol-ivan.xyz;

    # Carpeta específica donde Certbot tirará el archivo de validación
    location /.well-known/acme-challenge/ {
      root /usr/share/nginx/html;
    }

    location /healthz {
        return 200 "ok"
        add_header Content-Type text/plain
    }

    # Todo lo demás se va directo a HTTPS
    location / {
      return 301 https://$host$request_uri;
    }
  }

  # 2. Bloque HTTPS Seguro (Tu tráfico real)
  # server {
  #   listen 8443 ssl; 
  #   server_name smol-ivan.xyz www.smol-ivan.xyz;
  #
  #   root   /usr/share/nginx/html;
  #   index  index.html index.htm;
  #
  #   ssl_certificate /etc/letsencrypt/live/smol-ivan.xyz/fullchain.pem;
  #   ssl_certificate_key /etc/letsencrypt/live/smol-ivan.xyz/privkey.pem;
  #
  #   ssl_protocols TLSv1.2 TLSv1.3;
  #   ssl_ciphers HIGH:!aNULL:!MD5;
  #
  #   # Hardening y optimización en HTTPS
  #   gzip on;
  #   gzip_min_length 1000;
  #   gzip_proxied expired no-cache no-store private auth;
  #   gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
  #
  #   error_page 404 /404.html;
  #   location = /404.html {
  #     root /usr/share/nginx/html;
  #     internal;
  #   }
  #
  #   location / {
  #     try_files $uri $uri/index.html =404;
  #   }
  # }
}
