name: Integration

on:
    pull_request:
        branches:
            - main
        types: [opened, reopened, ready_for_review, synchronize]

jobs:
    validate-astro:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Node.js configuration
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Format validation (Prettier)
              run: pnpm exec prettier --check .

            - name: Check typos and astro code specifics
              run: pnpm run check

    validate-docker:
        runs-on: ubuntu-latest
        needs: validate-astro
        steps:
            - name: Code checkout
              uses: actions/checkout@v4

            - name: Test docker image building
              run: |
                  docker build \
                    -t smol-ivan-web:test \
                    -f Dockerfile .
